/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class media_protocol_gtec_NativeAmplifierC */

#ifndef _Included_media_protocol_gtec_NativeAmplifierC
#define _Included_media_protocol_gtec_NativeAmplifierC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    getHeaderSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_media_protocol_gtec_NativeAmplifierC_getHeaderSize
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    getSizeOfFloat
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_media_protocol_gtec_NativeAmplifierC_getSizeOfFloat
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    getDriverVersion
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_media_protocol_gtec_NativeAmplifierC_getDriverVersion
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    probeDevice
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_probeDevice
  (JNIEnv *, jobject, jint);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    openDevice
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_openDevice__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    openDevice
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_openDevice__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    closeDevice
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_closeDevice
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    getData
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_media_protocol_gtec_NativeAmplifierC_getData
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    setBufferSize
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_setBufferSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    setSampleRate
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_setSampleRate
  (JNIEnv *, jobject, jint);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    start
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_start
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    stop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_stop
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    setChannels
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_setChannels
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    setDigitalOut
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_setDigitalOut
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    getDigitalIO
 * Signature: ([Z[Z)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_getDigitalIO
  (JNIEnv *, jobject, jbooleanArray, jbooleanArray);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    getLastError
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_media_protocol_gtec_NativeAmplifierC_getLastError
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    getLastErrorCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_media_protocol_gtec_NativeAmplifierC_getLastErrorCode
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    getLastErrorMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_media_protocol_gtec_NativeAmplifierC_getLastErrorMessage
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    resetTransfer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_resetTransfer
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    getSerial
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_media_protocol_gtec_NativeAmplifierC_getSerial
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    enableTriggerLine
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_enableTriggerLine
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    getImpedance
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_media_protocol_gtec_NativeAmplifierC_getImpedance
  (JNIEnv *, jobject, jint);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    calibrate
 * Signature: ([F[F)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_calibrate
  (JNIEnv *, jobject, jfloatArray, jfloatArray);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    setScale
 * Signature: ([F[F)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_setScale
  (JNIEnv *, jobject, jfloatArray, jfloatArray);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    getScale
 * Signature: ([F[F)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_getScale
  (JNIEnv *, jobject, jfloatArray, jfloatArray);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    getFilterSpec
 * Signature: ([FI)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_getFilterSpec
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    getNumberOfFilters
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_media_protocol_gtec_NativeAmplifierC_getNumberOfFilters
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    setBandPass
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_setBandPass
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    getNotchFilterSpec
 * Signature: ([FI)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_getNotchFilterSpec
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    getNumberOfNotchFilters
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_media_protocol_gtec_NativeAmplifierC_getNumberOfNotchFilters
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    setNotch
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_setNotch
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    setMode
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_setMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    getMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_media_protocol_gtec_NativeAmplifierC_getMode
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    setGround
 * Signature: ([Z)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_setGround
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    getGround
 * Signature: ([Z)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_getGround
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    setReference
 * Signature: ([Z)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_setReference
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    getReference
 * Signature: ([Z)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_getReference
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    setBipolar
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_setBipolar
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    setDRLChannel
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_setDRLChannel
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    enableSC
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_enableSC
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    setSlave
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_setSlave
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     media_protocol_gtec_NativeAmplifierC
 * Method:    setDAC
 * Signature: (BIII)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierC_setDAC
  (JNIEnv *, jobject, jbyte, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
