/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class media_protocol_gtec_NativeAmplifierB */

#ifndef _Included_media_protocol_gtec_NativeAmplifierB
#define _Included_media_protocol_gtec_NativeAmplifierB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    getHeaderSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_media_protocol_gtec_NativeAmplifierB_getHeaderSize
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    getSizeOfFloat
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_media_protocol_gtec_NativeAmplifierB_getSizeOfFloat
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    getDriverVersion
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_media_protocol_gtec_NativeAmplifierB_getDriverVersion
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    probeDevice
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_probeDevice
  (JNIEnv *, jobject, jint);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    openDevice
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_openDevice__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    openDevice
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_openDevice__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    closeDevice
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_closeDevice
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    getData
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_media_protocol_gtec_NativeAmplifierB_getData
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    setBufferSize
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_setBufferSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    setSampleRate
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_setSampleRate
  (JNIEnv *, jobject, jint);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    start
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_start
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    stop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_stop
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    setChannels
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_setChannels
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    setDigitalOut
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_setDigitalOut
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    getDigitalIO
 * Signature: ([Z[Z)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_getDigitalIO
  (JNIEnv *, jobject, jbooleanArray, jbooleanArray);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    getLastError
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_media_protocol_gtec_NativeAmplifierB_getLastError
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    getLastErrorCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_media_protocol_gtec_NativeAmplifierB_getLastErrorCode
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    getLastErrorMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_media_protocol_gtec_NativeAmplifierB_getLastErrorMessage
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    resetTransfer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_resetTransfer
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    getSerial
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_media_protocol_gtec_NativeAmplifierB_getSerial
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    enableTriggerLine
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_enableTriggerLine
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    getImpedance
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_media_protocol_gtec_NativeAmplifierB_getImpedance
  (JNIEnv *, jobject, jint);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    calibrate
 * Signature: ([F[F)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_calibrate
  (JNIEnv *, jobject, jfloatArray, jfloatArray);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    setScale
 * Signature: ([F[F)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_setScale
  (JNIEnv *, jobject, jfloatArray, jfloatArray);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    getScale
 * Signature: ([F[F)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_getScale
  (JNIEnv *, jobject, jfloatArray, jfloatArray);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    getFilterSpec
 * Signature: ([FI)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_getFilterSpec
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    getNumberOfFilters
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_media_protocol_gtec_NativeAmplifierB_getNumberOfFilters
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    setBandPass
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_setBandPass
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    getNotchFilterSpec
 * Signature: ([FI)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_getNotchFilterSpec
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    getNumberOfNotchFilters
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_media_protocol_gtec_NativeAmplifierB_getNumberOfNotchFilters
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    setNotch
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_setNotch
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    setMode
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_setMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    getMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_media_protocol_gtec_NativeAmplifierB_getMode
  (JNIEnv *, jobject);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    setGround
 * Signature: ([Z)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_setGround
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    getGround
 * Signature: ([Z)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_getGround
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    setReference
 * Signature: ([Z)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_setReference
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    getReference
 * Signature: ([Z)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_getReference
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    setBipolar
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_setBipolar
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    setDRLChannel
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_setDRLChannel
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    enableSC
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_enableSC
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    setSlave
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_setSlave
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     media_protocol_gtec_NativeAmplifierB
 * Method:    setDAC
 * Signature: (BIII)Z
 */
JNIEXPORT jboolean JNICALL Java_media_protocol_gtec_NativeAmplifierB_setDAC
  (JNIEnv *, jobject, jbyte, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
