/*
 * ChannelSignalPanel.java
 *
 * Created on 29. April 2007, 07:57
 */

package visual_signal_components.passive_rendering;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author  Urkman_2
 */

public class ChannelSignalPanel extends JPanel{
    
    SpinnerNumberModel spinnerNumberModel;
    
    /**
     * Creates new form ChannelSignalPanel
     */
    public ChannelSignalPanel() {
        initComponents();
        spinnerNumberModel = new SpinnerNumberModel();
        spinnerNumberModel.setStepSize(1);
        spinnerNumberModel.setValue(1);
        getChannelSpinner().setModel(spinnerNumberModel);
    }
    
    public void setMaximum(int aVal){
        spinnerNumberModel.setMaximum(aVal);
    }
    
    public void setMinimum(int aVal){
        spinnerNumberModel.setMinimum(aVal);
    }
    
    public JPanel getUIComponentsPanel() {
        return uiComponentsPanel;
    }
    
    public JPanel getToolsRootPanel() {
        return toolsRootPanel;
    }
    
    public JSpinner getChannelSpinner() {
        return channelSpinner;
    }
    
    public JLabel getChannelLabel() {
        return channelLabel;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        toolsRootPanel = new javax.swing.JPanel();
        channelLabel = new javax.swing.JLabel();
        uiComponentsPanel = new javax.swing.JPanel();
        channelSpinner = new javax.swing.JSpinner();

        setLayout(new java.awt.BorderLayout());

        toolsRootPanel.setLayout(new java.awt.BorderLayout());

        channelLabel.setText("Channel ");
        toolsRootPanel.add(channelLabel, java.awt.BorderLayout.WEST);

        uiComponentsPanel.setLayout(new java.awt.BorderLayout());

        channelSpinner.setMinimumSize(new java.awt.Dimension(40, 20));
        channelSpinner.setPreferredSize(new java.awt.Dimension(40, 20));
        uiComponentsPanel.add(channelSpinner, java.awt.BorderLayout.WEST);

        toolsRootPanel.add(uiComponentsPanel, java.awt.BorderLayout.CENTER);

        add(toolsRootPanel, java.awt.BorderLayout.SOUTH);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel channelLabel;
    private javax.swing.JSpinner channelSpinner;
    private javax.swing.JPanel toolsRootPanel;
    private javax.swing.JPanel uiComponentsPanel;
    // End of variables declaration//GEN-END:variables
    
}