/*
 * BottomMenuFrame.java
 *
 * Created on 17. August 2007, 19:32
 */

package adracer;

import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author  Administrator
 */
public class BottomMenuFrame extends JFrame {
    
    public static String CALIBRATE_TRACKER_BUTTON = "CALIBRATE_TRACKER_BUTTON";
    public static String START_STOP_TRACKER_BUTTON = "START_STOP_TRACKER_BUTTON";
    public static String START_STOP_EEG_BUTTON = "START_STOP_EEG_BUTTON";
    public static String EXPORT_STATE_MONITOR = "EXPORT_STATE_MONITOR";
    public static String START_STOP_TRACKER_EXPORT = "START_STOP_TRACKER_EXPORT";
    
    /** Creates new form BottomMenuFrame */
    public BottomMenuFrame() {
        initComponents();
    }

    public JButton getStartStopTrackerExportButton() {
        return startStopTrackerExportButton;
    }

    public void setStartStopTrackerExportButton(JButton startStopTrackerExportButton) {
        this.startStopTrackerExportButton = startStopTrackerExportButton;
    }

    public JButton getCalibrateTrackerButton() {
        return calibrateTrackerButton;
    }

    public JButton getStartStopEEGButton() {
        return startStopEEGButton;
    }

    public JButton getStartStopTrackerButton() {
        return startStopTrackerButton;
    }

    public void setCalibrateTrackerButton(JButton calibrateTrackerButton) {
        this.calibrateTrackerButton = calibrateTrackerButton;
    }

    public void setStartStopEEGButton(JButton startStopEEGButton) {
        this.startStopEEGButton = startStopEEGButton;
    }

    public void setStartStopTrackerButton(JButton startStopTrackerButton) {
        this.startStopTrackerButton = startStopTrackerButton;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        calibrateTrackerButton = new javax.swing.JButton();
        startStopTrackerButton = new javax.swing.JButton();
        startStopEEGButton = new javax.swing.JButton();
        startStopTrackerExportButton = new javax.swing.JButton();
        enableExternalTriggerButton = new javax.swing.JButton();
        exportStateMonitorButton = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.FlowLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        calibrateTrackerButton.setText("Calibrate Tracker");
        getContentPane().add(calibrateTrackerButton);

        startStopTrackerButton.setText("Tracker is stopped");
        getContentPane().add(startStopTrackerButton);

        startStopEEGButton.setText("EEG is stopped");
        getContentPane().add(startStopEEGButton);

        startStopTrackerExportButton.setText("DB Export is stopped");
        getContentPane().add(startStopTrackerExportButton);

        enableExternalTriggerButton.setText("External trigger");
        getContentPane().add(enableExternalTriggerButton);

        exportStateMonitorButton.setText("Export State Monitor");
        getContentPane().add(exportStateMonitorButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setExportStateMonitorButton(JButton exportStateMonitorButton) {
        this.exportStateMonitorButton = exportStateMonitorButton;
    }

    public void setEnableExternalTriggerButton(JButton enableExternalTriggerButton) {
        this.enableExternalTriggerButton = enableExternalTriggerButton;
    }

    public JButton getExportStateMonitorButton() {
        return exportStateMonitorButton;
    }

    public JButton getEnableExternalTriggerButton() {
        return enableExternalTriggerButton;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BottomMenuFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calibrateTrackerButton;
    private javax.swing.JButton enableExternalTriggerButton;
    private javax.swing.JButton exportStateMonitorButton;
    private javax.swing.JButton startStopEEGButton;
    private javax.swing.JButton startStopTrackerButton;
    private javax.swing.JButton startStopTrackerExportButton;
    // End of variables declaration//GEN-END:variables
    
}
