/*
 * TopMenuFrame.java
 *
 * Created on 16. August 2007, 16:47
 */

package adracer;

import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author  Administrator
 */
public class TopMenuFrame extends JFrame {
    public static final String EYETRACKER_BUTTON = "EYETRACKER_BUTTON";
    public static final String GAZE_BUTTON = "GAZE_BUTTON";
    public static final String MULTICHANNEL_EEG_BUTTON = "MULTICHANNEL_EEG_BUTTON";
    public static final String SINGLE_CHANNEL_EEG_BUTTON = "SINGLE_CHANNEL_EEG_BUTTON";
    public static final String SUBBAND_EEG_BUTTON = "SUBBAND_EEG_BUTTON";
    public static final String ENERGY_BANDS_BUTTON = "ENERGY_BANDS_BUTTON";
    public static final String POWER_BANDS_BUTTON = "POWER_BANDS_BUTTON";
    public static final String CAMERA_BUTTON = "CAMERA_BUTTON";
    
    /** Creates new form TopMenuFrame */
    public TopMenuFrame() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        eyeTrackerButton = new javax.swing.JButton();
        gazeButton = new javax.swing.JButton();
        multiChannelEEGButton = new javax.swing.JButton();
        singleChannelEEGButton = new javax.swing.JButton();
        subbandEEGButton = new javax.swing.JButton();
        energyBandButton = new javax.swing.JButton();
        powerBandButton = new javax.swing.JButton();
        cameraButton = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.FlowLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        eyeTrackerButton.setText("EyeTracker");
        getContentPane().add(eyeTrackerButton);

        gazeButton.setText("GazeTracker");
        getContentPane().add(gazeButton);

        multiChannelEEGButton.setText("Multichannel EEG");
        getContentPane().add(multiChannelEEGButton);

        singleChannelEEGButton.setText("Singlechannel EEG");
        getContentPane().add(singleChannelEEGButton);

        subbandEEGButton.setText("Subband EEG");
        getContentPane().add(subbandEEGButton);

        energyBandButton.setText("Energy Bands");
        getContentPane().add(energyBandButton);

        powerBandButton.setText("Power Bands");
        getContentPane().add(powerBandButton);

        cameraButton.setText("Camera");
        getContentPane().add(cameraButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TopMenuFrame().setVisible(true);
            }
        });
    }

    public JButton getGazeButton() {
        return gazeButton;
    }

    public void setGazeButton(JButton gazeButton) {
        this.gazeButton = gazeButton;
    }

    public JButton getCameraButton() {
        return cameraButton;
    }

    public JButton getEnergyBandButton() {
        return energyBandButton;
    }

    public JButton getEyeTrackerButton() {
        return eyeTrackerButton;
    }

    public JButton getMultiChannelEEGButton() {
        return multiChannelEEGButton;
    }

    public JButton getPowerBandButton() {
        return powerBandButton;
    }

    public JButton getSingleChannelEEGButton() {
        return singleChannelEEGButton;
    }

    public JButton getSubbandEEGButton() {
        return subbandEEGButton;
    }

    public void setCameraButton(JButton cameraButton) {
        this.cameraButton = cameraButton;
    }

    public void setEnergyBandButton(JButton energyBandButton) {
        this.energyBandButton = energyBandButton;
    }

    public void setEyeTrackerButton(JButton eyeTrackerButton) {
        this.eyeTrackerButton = eyeTrackerButton;
    }

    public void setMultiChannelEEGButton(JButton multiChannelEEGButton) {
        this.multiChannelEEGButton = multiChannelEEGButton;
    }

    public void setPowerBandButton(JButton powerBandButton) {
        this.powerBandButton = powerBandButton;
    }

    public void setSingleChannelEEGButton(JButton singleChannelEEGButton) {
        this.singleChannelEEGButton = singleChannelEEGButton;
    }

    public void setSubbandEEGButton(JButton subbandEEGButton) {
        this.subbandEEGButton = subbandEEGButton;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cameraButton;
    private javax.swing.JButton energyBandButton;
    private javax.swing.JButton eyeTrackerButton;
    private javax.swing.JButton gazeButton;
    private javax.swing.JButton multiChannelEEGButton;
    private javax.swing.JButton powerBandButton;
    private javax.swing.JButton singleChannelEEGButton;
    private javax.swing.JButton subbandEEGButton;
    // End of variables declaration//GEN-END:variables
    
}
