/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class classification_ALNClassifier */

#ifndef _Included_classification_ALNClassifier
#define _Included_classification_ALNClassifier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     classification_ALNClassifier
 * Method:    init
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_classification_ALNClassifier_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     classification_ALNClassifier
 * Method:    classify
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_classification_ALNClassifier_classify
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
